# ビルド環境を構築してビルド
FROM ubuntu:xenial as build-env

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="666f88e2fcd83aabb6cb075ecca42b534f9afa2f"
LABEL description "athrill-gcc: 666f88e2fcd83aabb6cb075ecca42b534f9afa2f"

RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get -y install curl make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L https://github.com/tmori/athrill-gcc/releases/download/v1.0/athrill-gcc-package.tar.gz -O \
    && tar xf athrill-gcc-package.tar.gz \
    && cd athrill-gcc-package \
    && tar xf athrill-gcc.tar.gz -C / \
    && cd / \
    && rm -rf athrill-gcc-package \
    && rm athrill-gcc-package.tar.gz


FROM ubuntu:xenial

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="1.0"
LABEL description "version: v1.0"

RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get -y install make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build-env \
    /usr/local/athrill-gcc \
    /usr/local/athrill-gcc

ENV PATH="/usr/local/athrill-gcc/bin/:${PATH}" \
    LD_LIBRARY_PATH="/usr/local/athrill-gcc:/usr/local/athrill-gcc/lib:${LD_LIBRARY_PATH}"

# ネットワーク動通確認用ツール群インストール
RUN apt-get update \
    && apt-get -y install socat dnsutils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


